/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CustomerSession } from "./customersession.js";
import { Downloadables } from "./downloadables.js";
import { PagoBenefitGrants } from "./pagobenefitgrants.js";
import { PagoCustomerMeters } from "./pagocustomermeters.js";
import { PagoCustomers } from "./pagocustomers.js";
import { PagoLicenseKeys } from "./pagolicensekeys.js";
import { PagoMembers } from "./pagomembers.js";
import { PagoOrders } from "./pagoorders.js";
import { PagoOrganizations } from "./pagoorganizations.js";
import { PagoSubscriptions } from "./pagosubscriptions.js";
import { Seats } from "./seats.js";
import { Wallets } from "./wallets.js";

export class CustomerPortal extends ClientSDK {
  private _benefitGrants?: PagoBenefitGrants;
  get benefitGrants(): PagoBenefitGrants {
    return (this._benefitGrants ??= new PagoBenefitGrants(this._options));
  }

  private _customers?: PagoCustomers;
  get customers(): PagoCustomers {
    return (this._customers ??= new PagoCustomers(this._options));
  }

  private _customerMeters?: PagoCustomerMeters;
  get customerMeters(): PagoCustomerMeters {
    return (this._customerMeters ??= new PagoCustomerMeters(this._options));
  }

  private _seats?: Seats;
  get seats(): Seats {
    return (this._seats ??= new Seats(this._options));
  }

  private _customerSession?: CustomerSession;
  get customerSession(): CustomerSession {
    return (this._customerSession ??= new CustomerSession(this._options));
  }

  private _downloadables?: Downloadables;
  get downloadables(): Downloadables {
    return (this._downloadables ??= new Downloadables(this._options));
  }

  private _licenseKeys?: PagoLicenseKeys;
  get licenseKeys(): PagoLicenseKeys {
    return (this._licenseKeys ??= new PagoLicenseKeys(this._options));
  }

  private _members?: PagoMembers;
  get members(): PagoMembers {
    return (this._members ??= new PagoMembers(this._options));
  }

  private _orders?: PagoOrders;
  get orders(): PagoOrders {
    return (this._orders ??= new PagoOrders(this._options));
  }

  private _organizations?: PagoOrganizations;
  get organizations(): PagoOrganizations {
    return (this._organizations ??= new PagoOrganizations(this._options));
  }

  private _subscriptions?: PagoSubscriptions;
  get subscriptions(): PagoSubscriptions {
    return (this._subscriptions ??= new PagoSubscriptions(this._options));
  }

  private _wallets?: Wallets;
  get wallets(): Wallets {
    return (this._wallets ??= new Wallets(this._options));
  }
}
