/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @pago-sh/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx organizationsListOrganizations.example.ts
 */

import { Pago } from "@pago-sh/sdk";

const pago = new Pago({
  accessToken: process.env["PAGO_ACCESS_TOKEN"] ?? "",
});

async function main() {
  const result = await pago.organizations.listOrganizations({});

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
